export const NIGERIAN_UNIVERSITIES = [
  // Federal Universities
  'Abubakar Tafawa Balewa University (ATBU)',
  'Ahmadu Bello University (ABU)',
  'Bayero University Kano (BUK)',
  'Federal University Birnin Kebbi',
  'Federal University Dutse',
  'Federal University Dutsin-Ma',
  'Federal University Gashua',
  'Federal University Gusau',
  'Federal University Kashere',
  'Federal University Lafia',
  'Federal University Lokoja',
  'Federal University Ndufu-Alike Ikwo (FUNAI)',
  'Federal University of Agriculture Abeokuta (FUNAAB)',
  'Federal University of Agriculture Makurdi',
  'Federal University of Petroleum Resources Effurun (FUPRE)',
  'Federal University of Technology Akure (FUTA)',
  'Federal University of Technology Minna (FUTMINNA)',
  'Federal University of Technology Owerri (FUTO)',
  'Federal University Otuoke',
  'Federal University Oye-Ekiti (FUOYE)',
  'Federal University Wukari',
  'Michael Okpara University of Agriculture Umudike',
  'Modibbo Adama University Yola',
  'National Open University of Nigeria (NOUN)',
  'Nigerian Defence Academy (NDA)',
  'Nnamdi Azikiwe University (NAU)',
  'Obafemi Awolowo University (OAU)',
  'University of Abuja',
  'University of Benin (UNIBEN)',
  'University of Calabar (UNICAL)',
  'University of Ibadan (UI)',
  'University of Ilorin (UNILORIN)',
  'University of Jos (UNIJOS)',
  'University of Lagos (UNILAG)',
  'University of Maiduguri (UNIMAID)',
  'University of Nigeria Nsukka (UNN)',
  'University of Port Harcourt (UNIPORT)',
  'University of Uyo (UNIUYO)',
  'Usmanu Danfodiyo University Sokoto',
  'Yusuf Maitama Sule University Kano',

  // State Universities
  'Abia State University',
  'Adamawa State University',
  'Adekunle Ajasin University',
  'Akwa Ibom State University',
  'Ambrose Alli University',
  'Anambra State University',
  'Bauchi State University',
  'Benue State University',
  'Bukar Abba Ibrahim University',
  'Cross River University of Technology',
  'Delta State University',
  'Ebonyi State University',
  'Ekiti State University',
  'Enugu State University of Science and Technology (ESUT)',
  'Gombe State University',
  'Ibrahim Badamasi Babangida University',
  'Ignatius Ajuru University of Education',
  'Imo State University',
  'Kaduna State University',
  'Kano University of Science and Technology',
  'Kebbi State University of Science and Technology',
  'Kogi State University',
  'Kwara State University',
  'Lagos State University (LASU)',
  'Ladoke Akintola University of Technology (LAUTECH)',
  'Madonna University',
  'Niger Delta University',
  'Nasarawa State University',
  'Olabisi Onabanjo University',
  'Ondo State University of Science and Technology',
  'Osun State University',
  'Oyo State Technical University',
  'Plateau State University',
  'Rivers State University',
  'Sokoto State University',
  'Tai Solarin University of Education',
  'Taraba State University',
  'Umaru Musa Yaradua University',
  'Yobe State University',
  'Zamfara State University',
  // Private Universities
  'Achievers University',
  'African University of Science and Technology',
  'Afe Babalola University',
  'Al-Hikmah University',
  'American University of Nigeria',
  'Augustine University',
  'Babcock University',
  'Bells University of Technology',
  'Bingham University',
  'Bowen University',
  'Calvin Foundation University',
  'Caritas University',
  'Chrisland University',
  'Christopher University',
  'Clifford University',
  'Coal City University',
  'Covenant University',
  'Crawford University',
  'Crescent University',
  'Edwin Clark University',
  'Elizade University',
  'Evangel University',
  'Fountain University',
  'Godfrey Okoye University',
  'Gregory University',
  'Hallmark University',
  'Hezekiah University',
  'Igbinedion University',
  'Joseph Ayo Babalola University',
  'Kings University',
  'Kola Daisi University',
  'Kwararafa University',
  'Landmark University',
  'Lead City University',
  'McPherson University',
  'Novena University',
  'Oduduwa University',
  'Pan-Atlantic University',
  'Paul University',
  'Redeemers University',
  'Renaissance University',
  'Rhema University',
  'Ritman University',
  'Salem University',
  'Samuel Adegboyega University',
  'Southwestern University',
  'Summit University',
  'Tansian University',
  'Trinity University',
  'University of Mkar',
  'Veritas University',
  'Wellspring University',
  'Wesley University',
  'Western Delta University',
  'Wisdom University',
  'Anchor University',
  'Legacy University',
  'Other'
]

export const DEPARTMENTS_BY_FACULTY = {
  'Engineering & Technology': [
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Engineering',
    'Electrical Electronics Engineering',
    'Mechanical Engineering',
    'Mechatronics Engineering',
    'Petroleum Engineering',
    'Agricultural Engineering',
    'Biomedical Engineering',
    'Environmental Engineering',
    'Food Engineering',
    'Industrial Engineering',
    'Marine Engineering',
    'Materials and Metallurgical Engineering',
    'Mining Engineering',
    'Production Engineering',
    'Structural Engineering',
    'Systems Engineering',
    'Telecommunication Engineering',
  ],
  'Computing & Information Sciences': [
    'Computer Science',
    'Information Technology',
    'Software Engineering',
    'Cyber Security',
    'Data Science',
    'Information Systems',
    'Computer and Information Science',
    'Artificial Intelligence',
    'Network Engineering',
  ],
  'Natural Sciences': [
    'Biochemistry',
    'Biology',
    'Botany',
    'Chemistry',
    'Environmental Science',
    'Geology',
    'Geophysics',
    'Mathematics',
    'Microbiology',
    'Physics',
    'Statistics',
    'Zoology',
    'Oceanography',
    'Meteorology',
  ],
  'Medicine & Health Sciences': [
    'Medicine and Surgery (MBBS)',
    'Nursing Science',
    'Pharmacy',
    'Medical Laboratory Science',
    'Physiotherapy',
    'Radiography',
    'Dentistry',
    'Optometry',
    'Public Health',
    'Health Information Management',
    'Environmental Health Science',
    'Nutrition and Dietetics',
    'Anatomy',
    'Physiology',
  ],
  'Agriculture & Veterinary': [
    'Agricultural Economics',
    'Agricultural Extension',
    'Agronomy',
    'Animal Science',
    'Crop Science',
    'Fisheries and Aquaculture',
    'Food Science and Technology',
    'Forestry and Wildlife',
    'Horticulture',
    'Soil Science',
    'Veterinary Medicine',
    'Agricultural Engineering',
  ],
  'Management & Social Sciences': [
    'Accounting',
    'Actuarial Science',
    'Banking and Finance',
    'Business Administration',
    'Business Management',
    'Cooperative and Rural Development',
    'Economics',
    'Entrepreneurship',
    'Finance',
    'Human Resource Management',
    'Insurance',
    'International Business',
    'Marketing',
    'Office Technology and Management',
    'Public Administration',
    'Taxation',
  ],
  'Arts, Humanities & Social Sciences': [
    'Archaeology',
    'Christian Religious Studies',
    'Communication and Language Arts',
    'English and Literary Studies',
    'French',
    'Geography',
    'History and International Studies',
    'History and International Relations',
    'Islamic Studies',
    'Linguistics',
    'Mass Communication',
    'Music',
    'Nigerian Languages',
    'Peace and Conflict Studies',
    'Philosophy',
    'Political Science',
    'Psychology',
    'Religious Studies',
    'Sociology',
    'Social Work',
    'Theatre Arts',
    'Urban and Regional Planning',
  ],
  'Law': [
    'Law (LLB)',
    'Islamic Law',
    'International Law',
  ],
  'Education': [
    'Adult Education',
    'Business Education',
    'Early Childhood Education',
    'Educational Administration',
    'Educational Technology',
    'English Education',
    'Guidance and Counselling',
    'Health Education',
    'Home Economics Education',
    'Library and Information Science',
    'Mathematics Education',
    'Physical and Health Education',
    'Science Education',
    'Social Studies Education',
    'Special Education',
    'Technical Education',
    'Vocational Education',
  ],
  'Environmental Sciences': [
    'Architecture',
    'Building',
    'Estate Management',
    'Fine and Applied Arts',
    'Industrial Design',
    'Quantity Surveying',
    'Surveying and Geo-Informatics',
    'Town Planning',
    'Urban and Regional Planning',
  ],
}

export const AREAS_BY_FACULTY = {
  'Computing & Information Sciences': ['Artificial Intelligence', 'Cybersecurity', 'Web Development', 'Mobile Applications', 'Database Systems', 'Machine Learning', 'Networking', 'Cloud Computing', 'IoT Systems'],
  'Engineering & Technology': ['Automation', 'Embedded Systems', 'Renewable Energy', 'Structural Analysis', 'Process Engineering', 'Control Systems', 'Robotics'],
  'Management & Social Sciences': ['Financial Management', 'Marketing Strategy', 'Human Resources', 'Entrepreneurship', 'Supply Chain', 'Corporate Governance', 'Digital Marketing'],
  'Natural Sciences': ['Laboratory Research', 'Environmental Analysis', 'Computational Modelling', 'Field Study', 'Experimental Research'],
  'Medicine & Health Sciences': ['Clinical Research', 'Public Health', 'Epidemiology', 'Health Systems', 'Pharmacology', 'Community Health'],
  'Arts, Humanities & Social Sciences': ['Content Analysis', 'Survey Research', 'Policy Analysis', 'Media Studies', 'Community Studies', 'Discourse Analysis'],
  'Law': ['Constitutional Law', 'Commercial Law', 'Human Rights', 'Criminal Justice', 'International Law', 'Cyber Law'],
  'Education': ['Curriculum Development', 'Educational Technology', 'Learner Assessment', 'Inclusive Education', 'STEM Education'],
  'Agriculture & Veterinary': ['Crop Production', 'Animal Husbandry', 'Agricultural Economics', 'Food Processing', 'Environmental Conservation'],
  'Environmental Sciences': ['Urban Design', 'Sustainable Architecture', 'Property Management', 'Geographic Information Systems'],
}

// Flat list for dropdowns
export const ALL_DEPARTMENTS = Object.values(DEPARTMENTS_BY_FACULTY).flat().sort()

export function getAreasForDepartment(dept) {
  for (const [faculty, depts] of Object.entries(DEPARTMENTS_BY_FACULTY)) {
    if (depts.includes(dept)) {
      return AREAS_BY_FACULTY[faculty] || ['General Research', 'Applied Study', 'Comparative Analysis', 'Case Study']
    }
  }
  return ['General Research', 'Applied Study', 'Comparative Analysis', 'Case Study']
}